name: HybridSurvival
main: de.yourplugin.hybrid.HybridSurvivalConfigPlugin
version: 1.0.0
api-version: 1.21
author: DeinName
description: Hybrid Survival Plugin mit Arnis-Integration, Straßen, Gebäuden und Deko.

commands:
  buybuilding:
    description: Kaufe ein Gebäude.
    usage: /buybuilding
  sellbuilding:
    description: Verkaufe ein Gebäude.
    usage: /sellbuilding
  listbuildings:
    description: Zeigt alle Gebäude in der Welt.
    usage: /listbuildings
  tpbuilding:
    description: Teleportiere dich zu einem Gebäude.
    usage: /tpbuilding

permissions:
  hybrid.building.buy:
    description: Erlaubt das Kaufen von Gebäuden.
    default: true
  hybrid.building.sell:
    description: Erlaubt das Verkaufen von Gebäuden.
    default: true
  hybrid.building.list:
    description: Erlaubt das Auflisten aller Gebäude.
    default: true
  hybrid.building.tp:
    description: Erlaubt das Teleportieren zu Gebäuden.
    default: op