name: HybridSurvivalConfig
main: de.yourplugin.hybrid.HybridSurvivalConfigPlugin
version: 1.0.0
api-version: 1.21
author: dwuptpuma
description: Hybrid Survival Plugin mit Gebäude-System

commands:
  buybuilding:
    description: Kaufe ein Gebäude
    usage: /buybuilding <Adresse>
    permission: hybrid.building.buy
  sellbuilding:
    description: Verkaufe ein Gebäude
    usage: /sellbuilding <Adresse>
    permission: hybrid.building.sell
  tpbuilding:
    description: Teleportiere dich zu einem Gebäude
    usage: /tpbuilding <Adresse>
    permission: hybrid.building.tp
  listbuildings:
    description: Zeige alle Gebäude
    usage: /listbuildings
    permission: hybrid.building.list

permissions:
  hybrid.building.*:
    description: Zugriff auf alle Gebäude-Befehle
    children:
      hybrid.building.buy: true
      hybrid.building.sell: true
      hybrid.building.tp: true
      hybrid.building.list: true
