# ============================================
# Hybrid Survival Plugin - Konfiguration
# ============================================

# ===== Kern-Features =====
progressive-detail: true         # Mehrere Detailstufen bei Arnis-Generierung
chunk-preload: true              # Chunks im Umkreis des Spielers vorladen
lazy-light: true                 # Lichtupdates verzögert ausführen
rpc-threading: true              # RPC-Aufrufe asynchron ausführen
paste-threading: true            # WorldEdit-Pasten asynchron ausführen

# ===== Gebäude & Immobilien =====
generate-buildings: true         # Gebäude beim Chunk-Load generieren
building-purchase: true          # Gebäude können gekauft werden
sign-purchase: true              # Kauf über Schilder möglich
osm-interiors: false             # Interieur aus OSM generieren
shop-system: false               # Shopsystem aktivieren
synchronize-height: true         # Bauhöhe mit Welt-Höhe synchronisieren

# ===== Arnis-Integration =====
arnis:
  path: "/usr/local/bin/arnis"   # Pfad zur Arnis-CLI
  bbox-radius-meters: 100        # Größe der Bounding Box in Metern

# ===== Straßen & Parkplätze =====
streets:
  enabled: true
  block: BLUE_ICE                # Material für Straßenkörper
  line-block: ICE                # Material für Straßenlinien
  width: 5                       # Standard-Straßenbreite
  line-width: 1                  # Breite der Straßenlinien
  sidewalks:
    enabled: false               # Gehwege optional aktivierbar
    block: STONE_BRICKS          # Standardblock für Gehwege

parkings:
  enabled: true
  block: PACKED_ICE              # Material für Parkflächen
  line-block: ICE                # Material für Parkplatzmarkierungen
  slot-size: "3x6"               # Größe eines Parkplatz-Slots (Breite x Länge)

# ===== Dekorationen & Infrastruktur =====
decorations:
  street-lamps:
    enabled: false
    schematic-path: schematics/lamps/   # Ordner mit Schem-Dateien
  trees:
    enabled: false
    schematic-path: schematics/trees/   # Ordner mit Schem-Dateien
  benches:
    enabled: false
    schematic-path: schematics/benches/ # Ordner mit Schem-Dateien

# ===== Performance =====
max-chunks-per-tick: 16          # Max. Chunks pro Tick laden
lights-per-tick: 2               # Anzahl Lichtupdates pro Tick
preload-radius: 16               # Umkreis zum Vorladen von Chunks
async-events: true               # Events asynchron behandeln
telemetry: true                  # Telemetrie aktivieren
chunk-cache: true                # Cache für Arnis-Daten aktivieren
prefetch-spawn: true             # Spawn-Bereich beim Start laden