name: HybridSurvival
version: 1.0.0
main: de.yourplugin.hybrid.HybridSurvivalConfigPlugin
api-version: 1.21
author: yourname
description: >
  Hybrid Survival Plugin mit Arnis-Integration, Building-System und optionalen Dekorationen (Lampen, Bäume, Bänke).
website: https://github.com/Ilikeminecraftservers/Worldgen

commands:
  buybuilding:
    description: Kaufe ein Gebäude, wenn du davorstehst
    usage: /<command>
  sellbuilding:
    description: Verkaufe dein Gebäude
    usage: /<command>
  tpbuilding:
    description: Teleportiere dich zu einem Gebäude per Adresse
    usage: /<command> <Adresse>
  listbuildings:
    description: Zeigt eine Liste aller Gebäude
    usage: /<command>