name: Build Plugin

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build with Gradle
        run: ./gradlew clean shadowJar --refresh-dependencies --stacktrace

      - name: Upload Plugin Artifact
        uses: actions/upload-artifact@v4
        with:
          name: HybridSurvivalPlugin
          path: build/libs/*.jar